homeassistant:
  name: Home
  latitude: !secret HOME_LATITUDE
  longitude: !secret HOME_LONGITUDE
  temperature_unit: C
  time_zone: Australia/Sydney
  elevation: 178

  customize: !include includes/customize.yaml

#http:
#  api_password: !secret HA_PASSWORD
#  server_port: 8123

# -- Enabled --
# discovery:
frontend:
history:
logbook:
sun:

############
# INCLUDES #
############
group: !include includes/groups.yaml
sensor: !include_dir_merge_list includes/sensors
device_tracker: !include includes/device_trackers.yaml
media_player: !include includes/media_players.yaml
scene: !include includes/scenes.yaml
notify: !include includes/notify.yaml
script: !include_dir_named includes/scripts
automation: !include_dir_merge_list includes/automation
input_boolean: !include includes/input_boolean.yaml
